import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Material Design 3 - Sistema de colores Casaliz
        'on-primary-container': '#9ac0aa',
        'surface-dim': '#d9dad9',
        'surface-bright': '#f9f9f8',
        'on-primary-fixed-variant': '#2c4e3d',
        'on-tertiary-container': '#f8a181',
        'tertiary-container': '#74361d',
        'secondary': '#735a31',
        'error-container': '#ffdad6',
        'on-primary': '#ffffff',
        'inverse-on-surface': '#f0f1f0',
        'secondary-fixed': '#ffdeac',
        'on-error': '#ffffff',
        'primary': '#163828',
        'on-surface': '#191c1c',
        'surface-container-lowest': '#ffffff',
        'surface-container': '#edeeed',
        'on-background': '#191c1c',
        'on-secondary-container': '#785f35',
        'background': '#f9f9f8',
        'primary-container': '#2d4f3e',
        'outline': '#727973',
        'secondary-container': '#fddba7',
        'error': '#ba1a1a',
        'on-secondary': '#ffffff',
        'primary-fixed': '#c5ebd4',
        'on-secondary-fixed': '#281900',
        'surface-container-high': '#e7e8e7',
        'surface-variant': '#e1e3e2',
        'surface-tint': '#436653',
        'surface-container-low': '#f3f4f3',
        'on-surface-variant': '#414844',
        'on-primary-fixed': '#002113',
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed': '#380d00',
        'inverse-primary': '#a9cfb9',
        'surface': '#f9f9f8',
        'tertiary': '#572109',
        'on-error-container': '#93000a',
        'secondary-fixed-dim': '#e3c290',
        'surface-container-highest': '#e1e3e2',
        'primary-fixed-dim': '#a9cfb9',
        'on-tertiary-fixed-variant': '#72351c',
        'inverse-surface': '#2e3131',
        'on-secondary-fixed-variant': '#59431c',
        'tertiary-fixed': '#ffdbce',
        'outline-variant': '#c1c8c2',
        'tertiary-fixed-dim': '#ffb59a',
      },
      fontFamily: {
        'headline': ['Newsreader', 'serif'],
        'body': ['Manrope', 'sans-serif'],
        'label': ['Manrope', 'sans-serif'],
      },
      borderRadius: {
        'none': '0',
        'sm': '0.25rem',
        'DEFAULT': '0.5rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.5rem',
        'full': '9999px',
      },
      animation: {
        'fade-in': 'fadeIn 0.6s ease-out',
        'slide-up': 'slideUp 0.8s ease-out',
        'scale-in': 'scaleIn 0.5s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(40px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        scaleIn: {
          '0%': { opacity: '0', transform: 'scale(0.9)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
      },
    },
  },
  plugins: [],
}

export default config
